// <auto-generated />
using System;
using IMS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IMS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108000001_RemoveItemPriceVariantUniqueConstraint")]
    partial class RemoveItemPriceVariantUniqueConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // This is a partial migration - the full model snapshot is in AppDbContextModelSnapshot.cs
            // This migration only removes the unique constraint from ItemPriceVariants
#pragma warning restore 612, 618
        }
    }
}
